name: PRMonitor
options:
  bundleIdPrefix: com.prmonitor
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "0.1.0"
  CURRENT_PROJECT_VERSION: 1
  SWIFT_VERSION: "5.9"
  ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  PRMonitor:
    type: application
    platform: macOS
    sources:
      - path: Sources/PRMonitor
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.prmonitor.app
      INFOPLIST_FILE: Resources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Resources/PRMonitor.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Resources/PRMonitor.entitlements
