name: PRMonitor
options:
  bundleIdPrefix: com.prmonitor
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "0.1.0"
  CURRENT_PROJECT_VERSION: 1
  SWIFT_VERSION: "5.9"
  ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  MenuBarExtraAccess:
    url: https://github.com/orchetect/MenuBarExtraAccess
    from: 1.0.0

targets:
  PRMonitor:
    type: application
    platform: macOS
    sources:
      - path: Sources/PRMonitor
      - path: Resources/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.prmonitor.app
      INFOPLIST_FILE: Resources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Resources/PRMonitor.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Resources/PRMonitor.entitlements
      properties:
        com.apple.security.network.client: true
    dependencies:
      - package: KeyboardShortcuts
      - package: MenuBarExtraAccess
    preBuildScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        script: |
          if command -v swiftlint &> /dev/null; then
            swiftlint --fix && swiftlint
          else
            echo "warning: SwiftLint not installed, install via 'brew install swiftlint'"
          fi
      - name: SwiftFormat
        basedOnDependencyAnalysis: false
        script: |
          if command -v swiftformat &> /dev/null; then
            swiftformat . --lint
          else
            echo "warning: SwiftFormat not installed, install via 'brew install swiftformat'"
          fi
